<div class="col-md-6 col-lg-3">
                    <div class="box">
                        <div class="img-box">
                            <img src="all.jpeg" width="100%" height="70%" alt="">
                        </div>
                        <div class="detail-box">
                            <h5>
                                ALL SEMESTERS PREVIOUS QUESTION PAPERS
                            </h5>

                            <a href="ALLPAPERS.PHP">
                                <span>
                Read More
              </span>

                            </a>
                        </div>
                    </div>
                </div> 